# Generated by Django 3.2.9 on 2021-12-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiece', models.TextField(max_length=400)),
                ('skills', models.TextField(max_length=100)),
            ],
        ),
    ]
